apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rest-api
  labels:
    app: rest-api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
      - name: rest-api
        image: docker.io/jirawat/rest-api:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
        resources:
          limits:
            cpu: 10m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 30Mi
      terminationGracePeriodSeconds: 30
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
  labels:
    app: rest-api
  name: rest-api
spec:
  backend:
    serviceName: rest-api
    servicePort: 80
  rules:
  - host: rest-api.test
    http:
      paths:
      - path: /
        backend:
          serviceName: rest-api
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rest-api
  labels:
    app: rest-api
spec:
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 31000
    protocol: TCP
    name: http
  selector:
    app: rest-api
  type: NodePort
---
